spring:
  datasource:
    username: postgres
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/smartmeter_db
    password: postgres
    initialize: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    secure-port-enabled: true
    non-secure-port-enabled: false
